name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        bash -c '
        pylint --rcfile=.pylintrc $(git ls-files '*.py');
        exit_code=$?;
        if [ $exit_code -eq 0 -o $exit_code -gt 2 ]; then
          exit 0
        else
          exit $exit_code
        fi;'
